// Local-only helpers: spawn a private anvil and deploy MockUSDC + FlyingMoney from the generated bytecode.
import { type ChildProcess, spawn, spawnSync } from 'node:child_process'
import { createServer } from 'node:net'
import { flyingMoneyAbi, flyingMoneyBytecode, mockUsdcAbi, mockUsdcBytecode } from '@flying-money/abi'
import {
  createPublicClient,
  createWalletClient,
  type Hex,
  http,
  type PublicClient,
  type TransactionReceipt,
} from 'viem'
import { mnemonicToAccount } from 'viem/accounts'
import { anvil as anvilChain } from 'viem/chains'

/** Anvil's well-known PUBLIC dev mnemonic. These accounts exist only on a local anvil; never fund them elsewhere. */
export const ANVIL_MNEMONIC = 'test test test test test test test test test test test junk'
export const anvilAccount = (i: number) => mnemonicToAccount(ANVIL_MNEMONIC, { addressIndex: i })

export const anvilAvailable = () => spawnSync('anvil', ['--version']).status === 0

async function freePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const s = createServer()
    s.listen(0, () => {
      const a = s.address()
      const port = typeof a === 'object' && a ? a.port : 0
      s.close(() => resolve(port))
    })
    s.on('error', reject)
  })
}

export async function startAnvil(): Promise<{ url: string; stop: () => void; proc: ChildProcess }> {
  const port = await freePort()
  const proc = spawn('anvil', ['--port', String(port), '--silent'], { stdio: 'ignore' })
  const url = `http://127.0.0.1:${port}`
  for (let i = 0; i < 100; i++) {
    try {
      const r = await fetch(url, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'eth_chainId', params: [] }),
      })
      if (r.ok) return { url, proc, stop: () => proc.kill() }
    } catch {}
    await new Promise((r) => setTimeout(r, 100))
  }
  proc.kill()
  throw new Error('anvil did not start (is Foundry installed?)')
}

export async function deployLocal(url: string): Promise<{
  pub: PublicClient
  usdc: Hex
  flyingMoney: Hex
  wait: (hash: Hex) => Promise<TransactionReceipt>
}> {
  const pub = createPublicClient({ chain: anvilChain, transport: http(url), pollingInterval: 50 }) as PublicClient
  const w = createWalletClient({ account: anvilAccount(0), chain: anvilChain, transport: http(url) })
  const wait = (hash: Hex) => pub.waitForTransactionReceipt({ hash, pollingInterval: 50 })
  const usdc = (await wait(await w.deployContract({ abi: mockUsdcAbi, bytecode: mockUsdcBytecode }))).contractAddress!
  const flyingMoney = (
    await wait(await w.deployContract({ abi: flyingMoneyAbi, bytecode: flyingMoneyBytecode, args: [usdc, 0n, 0n] }))
  ).contractAddress!
  return { pub, usdc, flyingMoney, wait }
}
