// Generates src/generated.ts from the Foundry build output (run `forge build` in contracts/ first).
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const out = join(here, '..', '..', '..', 'contracts', 'out')
const read = (file: string, name: string) =>
  JSON.parse(readFileSync(join(out, file, `${name}.json`), 'utf8')) as { abi: unknown; bytecode: { object: string } }

const fm = read('FlyingMoney.sol', 'FlyingMoney')
const mock = read('MockUSDC.sol', 'MockUSDC')
const src = `// GENERATED by scripts/gen-abi.ts from contracts/out. Do not edit.
export const flyingMoneyAbi = ${JSON.stringify(fm.abi, null, 2)} as const

/** Creation bytecode (for local anvil deployments and tests). */
export const flyingMoneyBytecode = '${fm.bytecode.object}' as const

export const mockUsdcAbi = ${JSON.stringify(mock.abi, null, 2)} as const

/** MockUSDC creation bytecode: LOCAL ANVIL ONLY (§7.3). */
export const mockUsdcBytecode = '${mock.bytecode.object}' as const
`
writeFileSync(join(here, '..', 'src', 'generated.ts'), src)
console.log('wrote src/generated.ts')
